config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users  do
    resources :workouts
  end
  resources :users
  resources :workouts
  resources :categories, except: [:destroy]


  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'


end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }


  scope :beginner, -> { where(level: 'Beginner') }
  scope :intermediate, -> { where(level: 'Intermediate') }
  scope :advanced, -> { where(level: 'Advanced') }
  scope :expert, -> { where(level: 'Expert') }

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      if @user.nil?
          flash[:danger] = "User not found"
          redirect_to users_path
      else
         @workouts = @user.workouts
      end
    else
      @workouts = Workout.all
    end
  end

  def new
     @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
     @workout.user = current_user
     if @workout.save
      flash[:success] = "Workout was successfully created"
      redirect_to workout_path(@workout)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @workout.update(workout_params)
      flash[:success] = "Workout was successfully updated"
      redirect_to workout_path(@workout)
    else
      render 'edit'
    end
  end

  def show
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      @workout = @user.workouts.find_by(id: params[:id])
      if @workout.nil?
        flash[:danger] = "Workout not found"
        redirect_to user_workouts_path(@user)
      end
    else
      @workout = Workout.find(params[:id])
    end
  end

  def destroy
    @workout.destroy
    flash[:success] = "Workout was successfully deleted"
    redirect_to workouts_path
  end


private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:title, :description, :level, :user_id, :category_id)
  end

  def require_same_user
    if current_user != @workout.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own workout"
      redirect_to root_path
    end
  end
end

app/views/workouts/_form.html.erb
<%= render 'shared/errors', obj: @workout %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@workout, :html => { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of workout", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
          <div class="col-sm-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of workout" %>
          </div>
        </div>

        <!-- Level Selection -->

        <div class="control-label col-sm-2">
          <%= f.label :level %>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
              <%= f.select :level,['Beginner','Intermediate','Advanced','Expert'], include_blank: "Select" %>

            </div>
          </div>
        </div>

      <div class="control-label col-sm-2">
        <%= f.label :categories %>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <%= f.collection_select :category_id, Category.order(:name),:id,:name, include_blank: "Select" %>

          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to workouts listing", workouts_path %> ]
    </div>

  </div>
</div>

app/views/workouts/_workout.html.erb
<% obj.each do |workout| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="workout-title">
          <%= link_to workout.title, workout_path(workout) %>
        </div>
        <div class="workout-body">
          <%= truncate(workout.description, length: 100) %>
          <div class="workout-meta-details">
            <small>Created by: <%=  workout.user.username if workout.user %>,
              <%= time_ago_in_words(workout.created_at) %> ago,
                  last updated: <%= time_ago_in_words(workout.updated_at) %> ago</small>
          </div>
        </div>
        <% if workout.category %>
          <p>Categories: <%= render workout.category %></p>
        <% end %>

        <% if logged_in? && (current_user == workout.user || current_user.admin?) %>
          <div class="workout-actions">
            <%= link_to "Edit this workout", edit_workout_path(workout), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this workout", workout_path(workout), method: :delete,
                                                data: { confirm: "Are you sure you want to delete this workout?" },
                                                class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1 align="center"> Edit Workout</h1>
<%= render 'form' %>

app/views/workouts/index.html.erb
<h1 align="center">Listing all workouts</h1>
<div align="center">

<%= render 'workout', obj: @workouts%>

</div>

app/views/workouts/new.html.erb
<h1 align="center"> Create a Workout</h1>
<%= render 'form' %>

app/views/workouts/show.html.erb
<h2 align="center">Title: <%= @workout.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <% if @workout.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by:</li>

          <li class="workout-title">
            <%= link_to @workout.user.username, user_path(@workout.user) %>
          </li>
          <li><small><%= pluralize(@workout.user.workouts.count, "workout") if @workout.user.workouts %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@workout.description) %>

      <%=  @workout.level %>

      <% if @workout.category %>
    <p>Categories: <%= render @workout.category %></p>
    <% end %>


  <div class="workout-actions">
    <% if logged_in? && (current_user == @workout.user || current_user.admin?) %>
      <%= link_to "Edit this workout", edit_workout_path(@workout), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this workout", workout_path(@workout), method: :delete,
                                          data: { confirm: "Are you sure you want to delete this workout?" },
                                          class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all workouts", workouts_path, class: "btn btn-xs btn-success" %>
  </div>
</div>