config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users  do
    resources :workouts
  end
  resources :users
  resources :workouts
  resources :categories, except: [:destroy]


  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'


end

app/models/category.rb
class Category < ApplicationRecord
  has_many :workouts, inverse_of: :category, autosave: true, dependent: :destroy
  has_many :users, through: :workouts

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

  # scope :arms, -> { where(name: 'Arms') }
  # scope :legs, -> { where(name: 'Legs') }
  # scope :shoulders, -> { where(name: 'Shoulders') }
  #
  # def self.category_type(type)
  #   Category.where(name: type)
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.all

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was updated successfully"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    if params[:user_id]
        @user = User.find_by(id: params[:user_id])
        @category = @user.categories.find_by(id: params[:id])
        if @category.nil?
          flash[:danger] = "category not found"
          redirect_to user_categories_path(@user)
        end
      else
        @category = Category.find(params[:id])
      end
  end

  # def destroy
  #   @category = Category.find(params[:id])
  #   flash[:success] = "Category was successfully deleted"
  #   redirect_to category_path
  # end
private

  def category_params
    params.require(:category).permit(:name, :user_id)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  [<%= link_to "Cancel request and return to workouts listing", workouts_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing all categories</h1>
<div align="center">
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="workout-title">
            <%= link_to category.name, category_path(category) %>
          </li>
          <li><small><%=  pluralize(category.workouts.count, "workout") %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center">Category: <%= @category.name %></h1>
<div align="center">
  <% if logged_in? && current_user.admin? %>
    <div class="row">
      <span class="badge"><%= link_to "Edit category name", edit_category_path(@category) %></span>
    </div>
  <% end %>
</div>
<%= render 'workouts/workout', obj: @category.workouts%>
<div align="center">
</div>